apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APP_NAME}-deployment
spec:
  selector:
    matchLabels:
      app: {APP_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: {APP_NAME}
    spec:
      containers:
        - name: {APP_NAME}
          image: 192.168.56.12/admin/st:{IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: {APP_NAME}-service
spec:
  type: NodePort
  selector:
    app: {APP_NAME}
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8080  #跟 Dockerfile 中 EXPOSE 的端口对应
      nodePort: 31111 # 外部访问端口
