apiVersion: apps/v1
kind: Deployment
metadata:
  name: myselfst-deployment
spec:
  selector:
    matchLabels:
      app: myselfst
  replicas: 1
  template:
    metadata:
      labels:
        app: myselfst
    spec:
      containers:
        - name: myselfst
          image: 192.168.56.12/admin/st:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: myselfst-service
spec:
  type: NodePort
  selector:
    app: myselfst
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8080  #跟 Dockerfile 中 EXPOSE 的端口对应
      nodePort: 31111 # 外部访问端口
