swagger: 2.0
info:
  version: 1.0.0
  description: ST SERVICE
  title: ST SERVICE
schemes:
- http
host: localhost
basePath: /st
tags:
- name: ST Microservice
  description: ST Starter Kit

paths:
  
  /version:
    get:
      tags:
      - ST Microservice
      summary: Get ST Server Version
      description: Get ST Mobile Application Version
      operationId: getRaoVersion
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/RaoVersionResponse'
        500:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/BaseResponse'           

definitions:
  #
  # ST Version Request Start
  #  
  MaoVersionRequest:
    type: object
    properties:
      appVersion:
        type: string
        description: version of Application
      staticVersion:
        type: string
        description: version of staticData
  #
  # ST Version Request End
  #  
    
  #
  # ST Version Response Handling Start
  #
  RaoVersionResponse:
    type: object
    properties:
      result:
        type: object
        $ref: '#/definitions/BaseResponseResult'
      data:
        type: object
        $ref: '#/definitions/RaoVersionResponseData'
        
  #
  # ST Version Response Handling End
  #
  
  ## Common Object
  BaseResponse:
    type: object
    properties:
      result:
        $ref: "#/definitions/BaseResponseResult"
        
  BaseResponseResult:
    type: object
    properties:
      code:
        type: string
        description: The result code
      message:
        type: string
        description: The description for the result
        
  RaoVersionResponseData:
    type: object
    properties:
      appVersion:
        type: string
        description: Version of Mobile Application
      staticVersion:
        type: string
        description: Version of Static Data
