swagger: 2.0
info:
  version: 1.0.0
  description: ST SERVICE
  title: ST SERVICE
schemes:
- http
host: localhost
basePath: /st
tags:
- name: ST Microservice
  description: ST Demo

paths:
  
  /version:
    get:
      tags:
      - ST Microservice
      summary: Get ST Server Version
      description: Get ST Mobile Application Version
      operationId: getSTVersion
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/STVersionResponse'
        500:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/BaseResponse'
  /branch:
    get:
      tags:
      - ST Microservice
      summary: Get Branch Location
      description: Get Branch Location
      operationId: getBranchLocation
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/BranchLocationResponse'
        500:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/BaseResponse'
  /fxrate:
    get:
      tags:
      - ST Microservice
      summary: Get Foreign Exchange Rate
      description: Get Foreign Exchange Rate
      operationId: getForeignExchangeRate
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ScbCurrency'
        500:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/BaseResponse'           

definitions:
  #
  # ST Version Request Start
  #  
  MaoVersionRequest:
    type: object
    properties:
      appVersion:
        type: string
        description: version of Application
      staticVersion:
        type: string
        description: version of staticData
  #
  # ST Version Request End
  #  
    
  #
  # ST Version Response Handling Start
  #
  STVersionResponse:
    type: object
    properties:
      result:
        type: object
        $ref: '#/definitions/BaseResponseResult'
      data:
        type: object
        $ref: '#/definitions/STVersionResponseData'
        
  #
  # ST Version Response Handling End
  #
  
  #
  #branch location Response Handling start
  #
  BranchLocationResponse:
    type: object
    properties:
      scbAnnotation:
        type: object
        description: the part of annotation
        $ref: '#/definitions/ScbAnnotation'
      scbDistrict:
        type: object
        description: the annotation corresponding district
        $ref: '#/definitions/ScbDistrict'
        
  #
  #branch location Response Handling start
  #
  
  ## Common Object
  BaseResponse:
    type: object
    properties:
      result:
        $ref: "#/definitions/BaseResponseResult"
        
  BaseResponseResult:
    type: object
    properties:
      code:
        type: string
        description: The result code
      message:
        type: string
        description: The description for the result
  ScbCurrency:
    type: object
    properties:
        
  STVersionResponseData:
    type: object
    properties:
      appVersion:
        type: string
        description: Version of Mobile Application
      staticVersion:
        type: string
        description: Version of Static Data